name: "CI/CD - Build, Deploy & Monitor"

on:
  workflow_run:
    workflows: ["Terraform Infrastructure"] # Wait for infra to finish
    types: [completed]
  workflow_dispatch: # Keeps your manual button just in case

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flask-app-repo
        run: |
          # We MUST move into the 'app' folder where your Dockerfile is
          cd app
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name devops-eks --region us-east-1

      - name: Deploy with Helm
        run: |
          # Using the helm chart in your 'helm/flask-app' folder
          helm upgrade --install flask-app ./helm/flask-app \
            --set image.repository=021891609039.dkr.ecr.us-east-1.amazonaws.com/flask-app-repo \
            --set image.tag=latest
            
      - name: Get Service URL
        run: |
          echo "Waiting for LoadBalancer to be assigned..."
          sleep 15
          # This gets the External IP (DNS) of your service
          SERVICE_URL=$(kubectl get svc flask-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "----------------------------------------------------------"
          echo "DEPLOYMENT SUCCESSFUL!"
          echo "Your Application URL is: http://$SERVICE_URL"
          echo "----------------------------------------------------------"      